#!/usr/bin/env perl

use strict;
use warnings;

my %tags;
while (<>) {
	chop;
	my @elm = split(/\t/, $_);
	for (@elm) {
		my ($key, $value) = split(/:/, $_, 2);
		if ($key eq 'tag') {
			$tags{$value}++;
		}
	}
}

for (sort { $tags{$a} <=> $tags{$b} } keys(%tags)) {
	print join("\t", $tags{$_}, $_), "\n";
}
