#!/usr/bin/env perl

use strict;
use warnings;

my %branches;
while (<>) {
	chop;
	my @elm = split(/\t/, $_);
	for (@elm) {
		my ($key, $value) = split(/:/, $_, 2);
		if ($key eq 'branchto') {
			my ($branchtag, $rev) = split(/,/, $value, 2);
			$branches{$branchtag}++;
		}
	}
}

for (sort { $branches{$a} <=> $branches{$b} } keys(%branches)) {
	print join("\t", $branches{$_}, $_), "\n";
}
